version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: ${DOCKER_DB_HOST}
    ports:
      - "${PORT}:${PORT}"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
